window.CUSTOM_OPPOSITES = {
  "cat": "dog",
  "kitten": "puppy",
  "dog": "cat",
  "lion": "deer",
  "tiger": "rabbit",
  "elephant": "mouse",
  "horse": "snail",
  "shark": "goldfish",
  "whale": "shrimp",
  "eagle": "worm",
  "snake": "hamster",
  "wolf": "sheep",
  "bear": "squirrel",
  "crocodile": "turtle",
  "dragon": "ant",

  "beach": "mountains",
  "sea": "desert",
  "ocean": "forest",
  "city": "village",
  "urban": "rural",
  "jungle": "arctic",
  "island": "mainland",
  "park": "factory",
  "school": "vacation",
  "home": "office",
  "heaven": "hell",

  "happy": "sad",
  "joy": "misery",
  "excited": "bored",
  "love": "hate",
  "calm": "anxious",
  "peaceful": "chaotic",
  "confident": "insecure",
  "brave": "afraid",
  "hopeful": "hopeless",
  "motivated": "lazy",
  "relaxed": "stressed",

  "big": "small",
  "large": "tiny",
  "tall": "short",
  "fast": "slow",
  "hot": "cold",
  "bright": "dark",
  "clean": "dirty",
  "new": "old",
  "young": "old",
  "rich": "poor",
  "strong": "weak",
  "easy": "difficult",
  "hard": "easy",
  "soft": "hard",
  "heavy": "light",
  "full": "empty",
  "open": "closed",
  "beautiful": "ugly",
  "good": "bad",
  "best": "worst",

  "near": "far",
  "close": "distant",
  "left": "right",
  "up": "down",
  "top": "bottom",
  "inside": "outside",
  "above": "below",
  "front": "back",
  "start": "end",
  "beginning": "finish",

  "early": "late",
  "morning": "night",
  "day": "night",
  "now": "later",
  "always": "never",
  "instant": "delayed",
  "quick": "slow",
  "fastest": "slowest",

  "healthy": "junk food",
  "salad": "burger",
  "fruit": "candy",
  "vegetables": "fast food",
  "fresh": "stale",
  "hot food": "cold food",
  "sweet": "bitter",
  "spicy": "bland",

  "online": "offline",
  "digital": "analog",
  "smartphone": "landline",
  "laptop": "typewriter",
  "ai": "manual",
  "automation": "manual work",
  "fast internet": "slow internet",
  "high tech": "low tech",

  "how to gain weight": "how to lose weight",
  "how to lose weight": "how to gain weight",
  "how to study": "how to procrastinate",
  "how to be productive": "how to waste time",
  "success": "failure",
  "improve": "worsen",
  "increase": "decrease",
  "build": "destroy",
  "create": "ruin",

  "motivational": "demotivational",
  "inspiring": "discouraging",
  "positive": "negative",
  "fun": "boring",
  "funny": "serious",
  "cool": "lame",
  "interesting": "dull",

  "pizza": "pasta",
  "pasta": "pizza",
  "burger": "salad",
  "near me": "far away from you",
  "me": "you"
};
